### ISSUE TITLE
为什么第一个QLearning的最优步数是-4？

### ISSUE THREAD

**Issue by hugo0819** [lansinuote/More_Simple_Reinforcement_Learning#1]
每走一步扣一分，达到最优时不止走了4步啊，这个是怎么算的呢？

**Comment by wjt0716-DJTU** [comment]
![image](https://github.com/lansinuote/More_Simple_Reinforcement_Learning/assets/118798890/10c268bb-135d-4db9-9db3-d679baffa80b)

你可以把运行过程中的data数据打印出来，我看了下是一共运行六步，到达终点的奖励为1，前五步的-5+1=-4

**Comment by hugo0819** [comment]
明白了，感谢
